import { app, BrowserWindow, Menu, session, WebContentsView } from 'electron';

// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
const isTestEnvironment = process.env.NODE_ENV === 'test';

if (!isTestEnvironment && require('electron-squirrel-startup')) {
  app.quit();
}

// Enables DI before app is ready
import 'reflect-metadata';

const createAppWebView = (): WebContentsView => {
  const appWebSession = session.fromPartition('persist:app-web-session');
  const webWsUrls = APP_CONFIG.WEB_CONFIGURATION?.WS_CONFIGURATION?.map(
    (it) => it.URL
  ).join(' ');
  const cspValue = `default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; connect-src 'self' ${webWsUrls};`;

  appWebSession.webRequest.onHeadersReceived((details, callback) => {
    callback({
      responseHeaders: {
        ...details.responseHeaders,
        'Content-Security-Policy': [cspValue]
      }
    });
  });

  const appWebView = new WebContentsView({
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
      session: appWebSession
    }
  });

  // eslint-disable-next-line @typescript-eslint/no-unused-vars
  appWebView.webContents.on('context-menu', (_event, _params) => {
    const menu = Menu.buildFromTemplate([
      { role: 'reload' },
      { type: 'separator' },
      { role: 'toggleDevTools' }
    ]);

    menu.popup();
  });

  appWebView.webContents.loadURL(APP_CONFIG.WEB_URL);

  return appWebView;
};

const createWindow = (): void => {
  const mainWindow = new BrowserWindow({
    height: 600,
    width: 800,
    webPreferences: { preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY }
  });

  mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);

  const appWebView = createAppWebView();

  mainWindow.contentView.addChildView(appWebView);

  const updateWebViewSize = () => {
    const { width, height } = mainWindow.getContentBounds();

    appWebView.setBounds({ x: 0, y: 0, width: width, height: height });
  };

  updateWebViewSize();

  mainWindow.on('resize', updateWebViewSize);
};

app.once('ready', function () {
  onReady();
});

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.once('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit();
  }
});

async function onReady() {
  try {
    await startup();
  } catch (error) {
    console.error(error);
  }
}

async function startup() {
  await import('./app/mh-main');
}
